server:
  port: 9968
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore/key.keystore
    key-store-password: mypassword
    key-store-type: PKCS12
    enabled: true
#    error when http2 + ssl enabled
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: athenader_route
          uri: https://apiextaws.tcbs.com.vn
          predicates:
            - Path=/athenader/v1/derivatives/**
          filters:
            - name: RewritePath
              args:
                regexp: "/athenader/v1/derivatives"
                replacement: "/athenader/v1/derivatives"
            - name: CustomResponseFilter
            - SetResponseHeader=content-type, application/json
logging:
  level:
#    io:
#      netty: DEBUG
#    reactor:
#      netty: DEBUG
    org:
      springframework:
        web:
          reactive:
            socket: TRACE
        cloud:
          gateway: TRACE
        reactive:
          socket: TRACE
