server:
  port: 9968
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore/key.keystore
    key-store-password: mypassword
    key-store-type: PKCS12
    enabled: true
#    error when http2 + ssl enabled
spring:
  application:
    name: gateway
logging:
  level:
    io:
      netty: TRACE
    reactor:
      netty: TRACE
    org:
      springframework:
        web:
          reactive:
            socket: TRACE
        cloud:
          gateway: TRACE
        reactive:
          socket: TRACE
