server:
  port: 8080
  http2:
    enabled: false
  ssl:
    key-store: classpath:keystore/key.keystore
    key-store-password: mypassword
    key-store-type: PKCS12
    enabled: true
#    error when http2 + ssl enabled
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: athenader_route
          uri: https://apiextaws.tcbs.com.vn
          predicates:
            - Path=/athenader/v1/derivatives/**
          filters:
            - name: RewritePath
              args:
                regexp: "/athenader/v1/derivatives"
                replacement: "/athenader/v1/derivatives"
            - name: CustomResponseFilter
            - SetResponseHeader=content-type, application/json
        - id: wss_aws_route
          uri: wss://athenaaws.tcbs.com.vn
          predicates:
            - Path=/aws/athena/v1/stream
          filters:
            - name: RewritePath
              args:
                regexp: "/aws/athena/v1/stream"
                replacement: "/athena/v1/stream"
        - id: wss_bank_route
          uri: wss://athenader.tcbs.com.vn
          predicates:
            - Path=/bank/athena/v1/stream
          filters:
            - name: RewritePath
              args:
                regexp: "/bank/athena/v1/stream"
                replacement: "/athena/v1/stream"
logging:
  level:
    io:
      netty: DEBUG
    reactor:
      netty: DEBUG
    org:
      springframework:
        web:
          reactive:
            socket: TRACE
        cloud:
          gateway: TRACE
        reactive:
          socket: TRACE
